server:
  port: 8762  # 表示的当前这个微服务的端口
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # Eureka Server地址 表示将当前的微服务注册到哪个Eureka Server注册中心
  instance:
    prefer-ip-address: true # 表示将ip地址注册到Eureka Server

spring:
  application:
    name: eureka-users # 当前应用的名称.用于注册到Eureka Server 以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: HL921124
    url: jdbc:mysql://127.0.0.1:3306/blogmanage?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT